# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-04 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is Correct?')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual', models.CharField(max_length=256, verbose_name='Manual')),
            ],
            options={
                'verbose_name': 'Manual',
                'verbose_name_plural': 'Manual',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Page')),
                ('question', models.TextField(verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256, verbose_name='Subject')),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.Manual', verbose_name='Manual')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is Correct?')),
                ('ref_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.Answer', verbose_name='Answer')),
                ('test_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.Test', verbose_name='Test')),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_model', models.CharField(max_length=256, verbose_name='Test Model')),
                ('questions', models.PositiveSmallIntegerField(verbose_name='Number of questions')),
            ],
            options={
                'verbose_name': 'Test Model',
                'verbose_name_plural': 'Test Models',
            },
        ),
        migrations.CreateModel(
            name='TestModelSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_from', models.PositiveSmallIntegerField(verbose_name='Weight from')),
                ('weight_to', models.PositiveSmallIntegerField(verbose_name='Weight to')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.Subject', verbose_name='Subject')),
                ('test_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.TestModel', verbose_name='Test Model')),
            ],
            options={
                'verbose_name': 'Test Model Subject',
                'verbose_name_plural': 'Test Model Subjects',
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.Question', verbose_name='Question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.Test', verbose_name='Test')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='test_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.TestModel', verbose_name='Test Model'),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.Subject', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.Question', verbose_name='Question'),
        ),
    ]
