# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-05 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testanswer',
            name='test_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.TestQuestion', verbose_name='Test Question'),
        ),
    ]
