# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0002_auto_20160805_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='manual',
        ),
        migrations.AddField(
            model_name='question',
            name='manual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examapp.Manual', verbose_name='Manual'),
        ),
    ]
