# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0003_auto_20160809_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='question_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Question number'),
        ),
    ]
