# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0004_testquestion_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='other_subjects',
            field=models.ManyToManyField(related_name='other_questions_set', to='examapp.Subject', verbose_name='Other subjects'),
        ),
    ]
