# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0005_question_other_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='other_subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='other_questions_set', to='examapp.Subject', verbose_name='Other subjects'),
        ),
    ]
